package lexer.daos;

/**
 * This file is automatically generated by the compiler tools.
 * Do not manually update! (Use the CompilerTools to regenerate.)
 **/
public enum TokenKind {

  // Internal token kinds
  BogusToken, EOF,

  // Keywords
  BoolType, Else, If, IntType, CharType, HexType, // Added CharType, HexType
  Program, Return, Then, While, From, Step, // Added From, Step

  // Operators
  NotEqual, And, Multiply, Plus, Minus,
  Divide, Less, LessEqual, Greater, GreaterEqual, // Added Greater, GreaterEqual
  Assign, Equal, Or,

  // Separators
  LeftParen, RightParen, Comma, LeftBrace, RightBrace, To, // Added To (=>)

  // Literals and Identifiers
  Identifier,  // Variable names like i, j, write
  IntLit,      // Integer literals like 7, 42
  CharLit,     // Added for char literals ("a")
  HexLit       // Added for hexadecimal literals (0x1a2F)
}
